### ISSUE TITLE
Segmentation fault on commit a81518f

### ISSUE THREAD

**Issue by koeppl** [lucaspr98/gcBB#5]
If I run the toy example explained in the `readme` without the python `psutil` packgae, I obtain a segmentation fault on the call `./gcBB dataset/ -k 3`.  It would be nicer to  check whether this package exists and prematurely abort the execution with a nice error message.
The current output is as follows.

```
mkdir: cannot create directory ‘tmp’: File exists
mkdir: cannot create directory ‘results’: File exists
=== PHASE 1 ===
Start computing SA, BWT and LCP for all files
Traceback (most recent call last):
  File "/home/luna/src/gcBB/egap/eGap", line 4, in <module>
    from psutil import virtual_memory
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "/home/luna/src/gcBB/egap/eGap", line 4, in <module>
    from psutil import virtual_memory
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "/home/luna/src/gcBB/egap/eGap", line 4, in <module>
    from psutil import virtual_memory
ModuleNotFoundError: No module named 'psutil'
All needed arrays computed!
Merging all pairs and computing document array (cda)
egap/eGap -m 2048 --em --bwt --lcp --cda --cbytes 1 --sl --slbytes 2  tmp/reads1.bwt  tmp/reads2.bwt  tmp/reads3.bwt  -o tmp/merge.dataset
Traceback (most recent call last):
  File "/home/luna/src/gcBB/egap/eGap", line 4, in <module>
    from psutil import virtual_memory
ModuleNotFoundError: No module named 'psutil'
All arrays merged
Start construction of colored BOSS and comparing genomes using BWSD for every pair
=== PHASE 2 ===
Segmentation fault
```

**Comment by felipelouza** [comment]
That is a good point. I added this checking before starting Phase 1: https://github.com/lucaspr98/gcBB/commit/37648d38d5ae910dafe20258debbd2cc4fdaf972
Thanks @koeppl!
